apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "doki.fullname" . }}-redis
  labels:
    app: {{ template "doki.name" . }}
    release: {{ .Release.Name | quote }}
spec:
  storageClassName: {{ .Values.redis.storageClass | default "standard" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi