apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup-job
  labels:
    app: {{ template "doki.name" . }}
    chart: {{ template "doki.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  schedule: {{ .Values.postgresql.backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:{{ .Values.postgresql.tag }}
              env:
                - name: PGPASSWORD
                  value: {{ .Values.postgresql.postgresqlPassword | quote }}
              command:
                - /bin/sh
                - -c
                - "pg_dumpall -h {{ .Release.Name }}-postgresql -U {{ .Values.postgresql.postgresqlUsername }} > /backup/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump"
          restartPolicy: OnFailure
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
            - name: backup-storage
              mountPath: /backup
          volumes:
            - name: postgresql-storage
              persistentVolumeClaim:
                claimName: {{ include "doki.fullname" . }}
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ include "doki.fullname" . }}-backup
      backoffLimit: 4
