apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pandora-next.fullname" . }}
  labels:
    app: {{ template "pandora-next.name" . }}
    release: {{ .Release.Name | quote }}
spec:
  storageClassName: {{ .Values.storage.storageClass | default "standard" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi